### ISSUE TITLE
Local API - Unable to set-up component

### ISSUE THREAD

**Issue by Woutoud** [ualex73/slide#15]
Following the instructions for local API, I am getting the following error from HA:

```
Logger: homeassistant.setup
Source: setup.py:481
First occurred: 18:50:35 (1 occurrences)
Last logged: 18:50:35

Unable to prepare setup for platform 'slide.cover': Unable to set up component.
```

And the next error:

```
Logger: homeassistant.setup
Source: setup.py:404
First occurred: 18:50:35 (1 occurrences)
Last logged: 18:50:35

Error during setup of component slide
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/slide/__init__.py", line 146, in async_setup
    username = config[DOMAIN][CONF_USERNAME]
               ~~~~~~^^^^^^^^
KeyError: 'slide'
```

The Slide is working fine using the native app from Google Play. Any way to further diagnose this? What seems to be the issue?

**Comment by Woutoud** [comment]
I reinstalled the custom component via HACS, things seem to work now.
