### ISSUE TITLE
Errors when adding Slide integration

### ISSUE THREAD

**Issue by pietervanharen** [ualex73/slide#8]
Despite the fix mentioned in #4 I still get errors when adding this integration to Home Assistant:

```
Error during setup of component slide

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 257, in _async_setup_component
    result = await task
  File "/config/custom_components/slide/__init__.py", line 146, in async_setup
    username = config[DOMAIN][CONF_USERNAME]
KeyError: 'slide'
```

`Unable to prepare setup for platform slide.cover: Unable to set up component.`

I've made sure I installed the integration before adding the credentials to the configuration.yaml. I also made sure the Slide is set to use the Local API

**Comment by sschouten** [comment]
i have the same error

**Comment by LuukDomhof** [comment]
@MightyRhapsody I'm running into the same issue. Have you managed to find a fix? The cloud configuration from both this integration and the official Slide integration both don't work either...

Would love to get back remote control of my curtains again :)

**Comment by MightyRhapsody** [comment]
@LuukDomhof unfortunately not. I'm still using the cloud API. I increased the `scan_interval` in my Home Assistant configuration, and that works for now. 
 
Though I received an e-mail a couple of days ago from the Slide team;

> Er is een grote update in de maak. Na deze update zal de verbinding tussen je telefoon en Slide standaard via je eigen lokale netwerk lopen.
>    
> Wat betekent dit?
> Ben je met je telefoon verbonden met hetzelfde WiFi-netwerk als Slide? Dan loopt de verbinding direct via het lokale netwerk.  
> Ben je niet thuis? dan maakt je telefoon verbinding via onze server. Ook buitenshuis kan je dus gewoon je Slide blijven bedienen.
>  
> Wat merk ik hiervan?
> Je zal niks merken van de update. Wel zorgt deze update ervoor Slide nog sneller reageert op je commando's als je thuis bent, én je hebt geen verbinding meer nodig met het internet om deze commando's uit te voeren.
>  
> Valt je internetverbinding uit? Met deze update kan je nog steeds de gordijnen open en sluiten via de app.
>
